site_name: Kooplex Documentation
site_url: https://kooplex.github.io/Manual/
theme:
  name: readthedocs
  highlightjs: true
  hijs_languages:
        - python
  features:
    - navigation.sections
  logo: static/logo-halfcolored.png

extra_css:
  - /docs/stylesheets/custom.css

markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
        toc_depth: 3

plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - Environments: 
    - Create and configure: environments.md
    - Storage and Folders: folderstructure.md
    - Package management: packagemanagement.md
    - Environment Images: images.md
  - 'Education':
    - Courses: education.md

  - Collaboration:
    - Projects: projects.md

  - External services:
    - Seafile: services/seafile.md
    - Gitea: services/gitea.md
    - Teleport: services/teleport.md
  
  - Reports:
    - Interactive Dashboards and Applications: reports.md

  - Settings:
    - Canvas: settings/canvas.md
    - Uset tokens and keys: settings/usertokens.md
  - FAQ:
    - General: FAQ/General.md

  - Admin guide:
    - Installation: admin/installation.md
    - Configuration: admin/configuration.md
    - User Management: admin/usermanagement.md
    - Maintenance: admin/maintenance.md
    - Backup and Restore: admin/backup.md
    - Upgrading Kooplex: admin/upgrading.md
